[build]
    command = "yarn build --environment=staging"

[context.master]
    command = "yarn build --environment=production"
    environment = { HOST="https://ceqr-app-prod.herokuapp.com", MAINTENANCE_START='01/01/23 00:00', MAINTENANCE_END='01/01/23 00:00' }

[context.deploy-preview]
    command = "yarn build --environment=review"
    environment = { HOST="https://ceqr-app-staging.herokuapp.com", MAINTENANCE_START='02/02/23 00:00', MAINTENANCE_END='06/03/23 00:00' }

# enable entry to app through routes other than /
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
